### ISSUE TITLE
Does not work, while other solutions do

### ISSUE THREAD

**Issue by unleashed7** [eriklins/InsideBlue-BLE-Tool#10]
While it can see the device, it throws the Failed to connect to device error. The logs show nothing why this could be happening.

The odd part is that I can connect to the device easily with something like this: [https://flux-dev.vercel.app/](https://flux-dev.vercel.app/)

**Comment by eriklins** [comment]
If you're using Windows 11 it might be related to issue #8. I couldn't get it working on Win11 with Lazarus and SimpleBLE DLL. I finally rewrote it in C, see https://github.com/eriklins/BLE-Scout. This works on Win11.

**Comment by unleashed7** [comment]
That makes sense, I do use Win 11. I've tried a couple others, the apps on MS Store work on Win11, like this one ([github version](versionhttps://github.com/sensboston/BLEConsole)) or python with bleak, etc.

**Comment by unleashed7** [comment]
BLE-Scout seems to work, thanks!
