### ISSUE TITLE
DLL SimpleBLE libraries

### ISSUE THREAD

**Issue by radim100** [eriklins/InsideBlue-BLE-Tool#5]
Hi , excellent repo . 
I have downloaded repo and installed in my work folder for Lazarus 2.2.2 under windows 10 64bit . 
When I try to compile / run app I get this message :
Failed to load SimpleBLE library .
I have copied 2  dll files from this repo (last release )  and place them into src and bin folders . But I am still getting the same message . 
Can you please advice where is a problem . Thanks

**Comment by eriklins** [comment]
Hi and thanks!

The DLLs just need to be present in the build folder (bin/Debug or bin/win64-x86_64) when running. Not sure why it wouldn't find it. What is the full path to your build directory? Does the pre-compiled binary run properly?

You could alternatively try to comment our {$DEFINE DYNAMIC_LOADING} in insideblue.lpr and simpleble.pas.

I'm using Lazarus 2.3.0 for building (installed with fpcupdeluxe, branch "trunk"), but not sure if this would make a difference.

**Comment by radim100** [comment]
Hi and thanks for your help .
 Yes I had DLLs in bin/Debug present but I am using 32 bit version of Lazarus and had 64 bit DLLs. placede in bin/Debug 
When I have downloaded and replaced with DLLs 32 bit version then program compiled and started . 
But since I am running 32 bit Lazarus compiled with 32 bit DLLs I get on program startup that BLE is disabled :( my Win10 is 64 bit)

Welcome to InsideBlue BLE Tool V0.6
Uses SimpleBLE version: 0.6.2
Bluetooth is disabled.
Init done.

Is this case correct ?  I would like to use these libs to write program which can be 32 bit ( so customers with older Win OS) can run it and at the same time it can be run on 64 bit WinOS . IS this achievable or under WinOS 64 bit I have to use 64 bit Lazarus ?

**Comment by eriklins** [comment]
This actually is a known issue with the underlying SimpleBLE library, see https://github.com/OpenBluetoothToolbox/SimpleBLE/issues/186.
From my understanding, the 32 bit version of the library only runs properly on a 32 bit Windows but not on 64 bit.

Unfortunately there is nothing to be done on InsideBlue or Lazarus side. Currently it would be required to have separate builds for 32 bit and 64 bit instead of just 32 bit running on both platforms.

**Comment by radim100** [comment]
Ok thanks . That is good to know . We will have to consider this issue . 
On a side topic - do you know some other BLE  Lazarus  libraries that can be used instead of Simple BLE ? 
We have looked into some of options for Windows OS , but there is not too much options .  
WCL is one of paid options (https://www.btframework.com/wcl_lazarus.htm)  - do you have any experience with that one ?
Can you direct us to other libraries ? 
Thanks ahead .

**Comment by eriklins** [comment]
I think that library has been mentioned in some Lazarus forum already but it's not open source, hence comes with cost and won't be the one I would use for my open source project. Before doing the Pascal bindings for SimpleBLE I looked around for other libraries but couldn't find any which was both recent and actively maintained, so I started with SimpleBLE.

**Comment by radim100** [comment]
Yes I have had the same experience with Lazarus BLE  libs.  I love Lazarus and do not want to switch to Delphi or some other IDE . 
Well thanks for you help .

**Comment by eriklins** [comment]
Closing this since due to SimpleBLE library.
